---
title: "DEEP: Future Fit"
author: "by Jess"
format:
    revealjs:
        theme: [solarized, custom.scss]
        slideNumber: true
        show-slide-number: all
        #reference-location: document
        #logo: images/logo.png
        footer: "https://deep-future-fit.netlify.app/"
        chalkboard:
            theme: whiteboard
        #code-annotations: hover
        css: styles.css
        mermaid:
          theme: default
        highlight-style: github
        #highlight-style: monochrome
        #logo: qr-code.png
        #multiplex: true
editor:
    render-on-save: true

---
# Review

::: {.notes}
blooket + discussion
:::

# Systems Programming

## Systems

- Operating Systems
- Embedded Systems
- Microcontrollers

## Computer Hardware

Every computer has a central processing unit (CPU) that executes instructions.

Types of CPU architectures:

- ARM (Raspberry Pi, Apple Silicon, Qualcomm Snapdragon)
- x86 (Intel/AMD CPUs)
- RISC-V

## Bluetooth Low-Energy (BLE)
Wireless communication designed for low-power, short-range communication.

What applications or use cases is BLE good for?

::: {.fragment .fade-in}
- Fitness trackers
- Healthcare devices
- Smart sensors
- Internet of Things (IoT) devices
:::

::: {.notes}
compare with bluetooth
:::

## Modes

Advertising: the device broadcasts its presence to nearby devices.

<br>

Connection: Bidirectional communication between central and peripheral devices.

## Services and Characteristics

Labels to organize BLE communication:

- Services: a group of related characteristics that provide a specific functionality.
- Characteristics: a single value that can be read or written by the central device.

## Profiles
BLE includes standard profiles that simplify development.

For example:

- Battery Service (0x180F)
    - Battery Level Characteristic (0x2A19)
- Heart Rate Service (0x180D)
    - Heart Rate Measurement Characteristic (0x2A37)

## Arduino
TODO

## Circuits
TODO

## Programming an Arduino
TODO

## Number Representations

- Decimal (0, 1, 2, 3, 4, 5, 6, 7, 8, 9)
- Binary (0, 1)
- Octal (0, 1, 2, 3, 4, 5, 6, 7)
- Hexadecimal (0-9, A, B, C, D, E, F)

::: {.notes}
hand out worksheet
:::

# 2 in binary?

::: {.notes}
take out ipad and show them how to compute values
:::

## Converting to Decimal (from non-Decimal)

1. Multiply each digit by its base raised to the power of its position (from
right to left, starting at 0).
2. Sum all the values obtained.

::: {.notes}
work through some examples with them
:::

## Converting to Binary (from Decimal)

1. Divide the decimal number by the base of the target system.
2. Write down the remainder.
3. Repeat the division with the quotient until the quotient becomes zero.
4. Read the remainders in reverse order (from last to first). This is the equivalent number in the target
base.

::: {.notes}
work through some examples with them
:::


## Bitwise Operators
```{.c}
// Bitwise operators: &, |, ^, ~, <<, >>
printf("  5 & 3  = %d  (0101 & 0011 = 0001)\n", 5 & 3);
printf("  5 | 3  = %d  (0101 | 0011 = 0111)\n", 5 | 3);
printf("  5 << 1 = %d  (left shift by 1)\n\n", 5 << 1);
```

# Tutorial


# Javascript


## Introduction 
- JavaScript is the **programming language for websites**.
- It can:
  - Calculate and manipulate data.
  - Update and modify HTML and CSS.
- Used to create interactive websites.






## Variables
JavaScript variables store data.

### `let`

Used when the value may change.

```js
let score = 10;
score = 20;
```

### `const`

Used when the variable should not be reassigned.

```js
const score = 10;
score = 20; // Error
```

Once assigned, a `const` variable cannot change to another value.




# Printing Output

## `console.log()`

```js
console.log("Hello");
```

Output:

```
Hello
```

## Multiple Values

```js
let a = 5;
let b = 10;

console.log(a, b);
```

Output:

```
5 10
```




## Operations
### Arithmetic Operators

```js
let a = 10;
let b = 3;
```

| Expression | Result |
|------------|--------|
| `a + b` | 13 |
| `a - b` | 7 |
| `a * b` | 30 |
| `a / b` | 3.333... |
| `a % b` | 1 |
| `a ** b` | 1000 |



## Operations
### Assignment Operators

```js
let x = 5;

x += 2;   // 7
x -= 1;   // 6
x *= 3;   // 18
x /= 2;   // 9
```

### Comparison Operators

```js
5 > 3;   // true
5 < 3;   // false
5 >= 5;  // true
5 <= 4;  // false
```

Comparison operators return either `true` or `false`.


## Operations
### Double Equals vs Triple Equals

#### Double Equals (`==`)

Performs type conversion or only value matteres.

```js
5 == "5";      // true
true == 1;     // true
false == 0;    // true
```

#### Triple Equals (`===`)

Checks both value and type.

```js
5 === 5;     // true
5 === "5";   // false
```

Examples:

```js
0 == false;   // true
0 === false;  // false
```

> With `===`, both the value and type must match.







## Functions
- arrow definition


## Callback Functions


## Array Functions






## Strings?


## Object Destructuring
