---
title: "DEEP: Future Fit"
author: "by Jess"
format:
    revealjs:
        theme: [solarized, custom.scss]
        slideNumber: true
        show-slide-number: all
        #reference-location: document
        #logo: images/logo.png
        footer: "https://deep-future-fit.netlify.app/"
        chalkboard:
            theme: whiteboard
        #code-annotations: hover
        css: styles.css
        mermaid:
          theme: default
        highlight-style: github
        #highlight-style: monochrome
        #logo: qr-code.png
        #multiplex: true
editor:
    render-on-save: true

---

# Review

# Debugging

::: {.notes}
how would i debug my app?
:::

## Tests

- Unit Tests
    - isolated tests for individual components
- End-to-End Tests
    - testing the entire application
- Regression Tests
    - ensuring existing functionality is not broken

::: {.fragment .fade-in}
How would you test the Google search engine?
:::

::: {.notes}
give examples of each
:::

## Performance Profiling

The performance of a function, program, or system depends on our goals.

What are some metrics we can use to measure performance?

::: {.fragment .fade-in}
Consider the metric of loading times. When might this metric NOT be a good measure for performance?
:::

::: {.notes}
login pages
:::

## Throughput
The rate at which data is successfully transmitted over a network from one point to another.

Why is high throughput good?

::: {.fragment .fade-in}
Why might we NOT want to increase throughput?
:::

::: {.notes}
telephone line example
:::

## Usage
The total amount of data transferred over a network.

Why is high usage good?

::: {.fragment .fade-in}
[A good network should balance throughput and usage.]{.highlight-red}
:::

# Adding Metrics

# Tutorial

# Demo
